// Copyright (c) 2026 Emanuele Ciotola. All Rights Reserved.
// PROJECT: G-Scanner — See LICENSE file in root for terms.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Vx5SInB0C1tqrli7eVYmT_2G_e_8VcI',
    appId: '1:1026607445667:web:117600814265f7c88e3116',
    messagingSenderId: '1026607445667',
    projectId: 'gscanner-5a2c9',
    authDomain: 'gscanner-5a2c9.firebaseapp.com',
    storageBucket: 'gscanner-5a2c9.firebasestorage.app',
    measurementId: 'G-34QCZ2CG83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVVkQ02iXJI_sQiBq7oN6t8vFHbZeZDw',
    appId: '1:1026607445667:android:c10ca7ddfb5fb9558e3116',
    messagingSenderId: '1026607445667',
    projectId: 'gscanner-5a2c9',
    storageBucket: 'gscanner-5a2c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1F9L3sdMoOZwYoeIiknzrhqbVSmIBNKI',
    appId: '1:1026607445667:ios:0f98edfde4fd19568e3116',
    messagingSenderId: '1026607445667',
    projectId: 'gscanner-5a2c9',
    storageBucket: 'gscanner-5a2c9.firebasestorage.app',
    iosBundleId: 'it.emanueleciotola.gscanner',
  );
}
