// Copyright (c) 2026 Emanuele Ciotola. All Rights Reserved.
// PROJECT: G-Scanner — See LICENSE file in root for terms.

const String ppEn = r'''
# Privacy Policy of G-Scanner

**Version:** 1.0

**Effective Date:** October 9, 2026

**Last Updated:** October 9, 2026

---

This Privacy Policy describes the procedures for the processing of personal data carried out through the **G-Scanner** mobile and web application, developed in compliance with **Regulation (EU) 2016/679 (GDPR)** and the applicable Italian legislation on personal data protection.

---

## Purpose of the Application

G-Scanner is an application that allows users to consult information related to food products by scanning barcodes, with particular attention to the needs of people suffering from celiac disease or lactose intolerance.

The application also allows users to configure specific dietary preferences, receive indications based on pre-set informational filters, and participate in a community by sharing product reports.

**Important – Limitation of Liability**

The information provided by G-Scanner is exclusively for informational and user support purposes.

The application **does not constitute a medical device**, **does not provide medical advice**, **has no diagnostic or therapeutic value**, and **does not produce legally binding effects or evaluations**.

The displayed information does not in any way replace:

* the advice of a doctor or other qualified healthcare professional;

* the consultation of the official food product labels;

* the information provided directly by the manufacturer.

The evaluations generated by the application are based exclusively on the data available in the database and the settings configured by the user, and may not reflect variations in product composition, recipe updates by manufacturers, or unavailable information.

The user is always required to independently verify the composition and labeling of products prior to consumption.

---

## 1. Data Controller

The Data Controller for the processing of personal data is:

**Emanuele Ciotola**

Email:

**[supporto-gscanner@googlegroups.com](mailto:supporto-gscanner@googlegroups.com)**

For any request concerning the processing of personal data or the exercise of rights under the GDPR, the Data Controller can be contacted at the aforementioned address.

---

## 2. Types of Data Processed

The application processes exclusively the data necessary for its operation and the provision of the offered features.

### 2.1 Anonymous users

When G-Scanner is used without logging in, the user's personal data and configured preferences remain exclusively on the device and are stored locally via **SharedPreferences**.

These include:

* scan history;

* application settings;

* preferences related to dietary and health features selected by the user.

Such personal data **is not transmitted to the Data Controller's servers**.

It is understood, however, that **product reports**, if submitted through the application, are stored in the application's cloud database and made available to other users of the community in order to improve the service.

Reports published in the community may exclusively contain:

* information relating to the reported food or product;

* any notes entered by the user;

* the reason for the report.

The identity of the reporting user, including **first name, last name, email address, or other identifying data**, **is never made public or visibly associated with the report under any circumstances**.

Reports made by other users can also be viewed by application users, regardless of authentication.

### 2.2 Authenticated users

The user may authenticate through **Firebase Authentication** using an account from:

* Google;

* Facebook.

Following authentication, the data necessary to identify the user is acquired from the provider, which may include:

* first name;

* last name;

* email address;

* phone number, where available or associated with the profile used for authentication.

A unique user identifier (**User ID**) is associated with this information.

G-Scanner does not access the user's authentication credentials, such as passwords or equivalent tools, and does not process such information.

### 2.3 Data stored in the cloud database

For authenticated users, the following data is stored on **Firebase Firestore**, associated with the user's identifier:

* scan history;

* list of submitted reports;

* settings related to dietary preferences:

Additives Warning;

* Strict Contamination Filter;

* Lactose Intolerance;

* any settings related to contamination warnings;

* selected language;

* chosen graphical theme.

The identifying data obtained through authentication (first name, last name, email address, and any available phone number) is used exclusively to:

* allow account management;

* correctly associate user data with their profile;

* provide features reserved for authenticated users.

### 2.4 Cookies and Local Storage Technologies

G-Scanner (both in the Web App version and the Mobile application) does not use profiling cookies, advertising tracking tools, or third-party analytics systems.

The application exclusively uses strictly necessary local storage technologies (such as SharedPreferences on mobile devices and LocalStorage / Technical cookies on browsers) for the sole purpose of:

* Safely maintaining the active user session via Firebase Authentication;

* Locally storing user preferences (e.g., language, graphical theme) and the confirmation of acceptance of legal documents.

Since these are exclusively technical tools strictly necessary for the provision of the service requested by the user, pursuant to European regulations (ePrivacy Directive) and the rulings of the Italian Data Protection Authority, prior user consent is not required for their use. The user is informed of their presence through this Privacy Policy, without the need for banners or separate documents.

Locally stored data remains on the user's device until deleted or until the application is uninstalled.

### 2.5 Local Database for Offline Use

G-Scanner may allow the user to download a local copy of data relating to food products to their device, in order to enable product consultation and scanning even in the absence of an Internet connection.

The offline database contains exclusively food product information necessary for the operation of offline features and does not contain any personal data of the user.

The user can choose between different offline database configurations, characterized by a different level of coverage and a consequent different amount of data stored on the device.

The data present in the offline database constitutes a local copy of the data available at the time of its update and may therefore not reflect subsequent modifications or updates to the product information.

Data consulted through the offline database is not automatically associated with the user's personal profile, nor is it used to create or update their profile.

The offline database can be updated or deleted by the user via the features made available by the application.

---

## 3. Special Categories of Personal Data (Art. 9 GDPR)

G-Scanner allows the user to configure specific personal preferences aimed at consulting information on food products. These settings may reflect the user's health status or particular dietary needs and, therefore, may constitute **special categories of personal data** under **Article 9 of Regulation (EU) 2016/679 (GDPR)**.

The settings available in the application are as follows:

* **Additives Warning**: generates a warning in the presence of ingredients such as modified starches or flavorings whose origin is not specified, allowing the user to perform further checks.

* **Strict Contamination Filter**: considers as **"Forbidden"** any food whose label contains statements such as **"may contain traces of gluten"** or equivalent wording relating to possible gluten contamination.

* **Lactose Intolerance**: checks for the presence of ingredients such as lactose, butter, milk powder, or whey, signaling their potential presence according to the application's functionality.

Upon the **first launch of the application**, only the following options are enabled by default:

* Additives Warning;

* Strict Contamination Filter.

The **Lactose Intolerance** option is initially disabled and can be enabled by the user at any time.

The processing of this information takes place **exclusively subject to the user's explicit consent**, pursuant to **Article 9, paragraph 2, letter a) of the GDPR**.

The user is free to modify, activate, or deactivate the aforementioned settings at any time according to their personal needs.

These choices are made under the user's responsibility, who acknowledges that G-Scanner is exclusively an **informational support tool** and does not replace:

* the verification of product labels;

* the information provided by the manufacturer;

* the advice of a doctor or other qualified healthcare professional.

Any modification to the settings and the use of the information provided by the application is therefore undertaken **at the user's sole risk**.

The user may at any time modify their preferences or withdraw previously given consent, without affecting the lawfulness of the processing carried out prior to the withdrawal.

---

## 4. Purposes of Processing

Personal data collected through G-Scanner is processed for the following purposes:

* allowing the scanning of barcodes and the consultation of information relating to food products;

* allowing the consultation of information relating to products even in the absence of an Internet connection, through any local database downloaded by the user;

* enabling the personalization of the user experience through the configuration of dietary preferences and application settings;

* allowing authenticated users to synchronize data across different devices;

* allowing participation in the community through the submission, management, and consultation of product reports;

* managing authentication via external providers such as Google and Facebook;

* ensuring the correct technical functioning of the application, the security of services, and the protection of processed data.

---

## 5. Legal Basis for Processing

The processing of personal data is based on:

* the explicit consent of the Data Subject for the processing of **special categories of personal data** concerning health (Art. 9, para. 2, lit. a GDPR);

* the performance of the service requested by the user and the features offered by the application;

* compliance with legal obligations provided by applicable law;

* the legitimate interest of the Data Controller regarding the technical security of the application and the prevention of improper use of the service, where applicable.

---

## 6. Minors

The use of G-Scanner is strictly prohibited to individuals under the age of **14**.

In compliance with Italian legislation on digital consent, the application is not intended for users under the age of 14 and does not knowingly collect personal data relating to such individuals.

If the Data Controller becomes aware of the presence of data belonging to a minor under 14, such data will be promptly deleted.

---

## 7. Access to Device Features and Information

To ensure the proper functioning of the offered features, G-Scanner may access certain features and information of the user's device.

### Camera

The camera is used exclusively to allow the scanning of product barcodes.

Images acquired via the camera are not saved, transmitted, or used for purposes other than barcode scanning.

### Internet Connection

The application checks, where necessary, the availability of an Internet connection in order to determine whether features requiring access to online services can be used.

An Internet connection is necessary, in particular, to:

* perform authentication via supported providers;

* synchronize data for authenticated users;

* access cloud services used by the application;

* retrieve and update product information via online services;

* enable the operation of features based on community data.

The connection status is used exclusively for the technical management of the application's features and is not collected, stored, or used for profiling or tracking purposes.

### System Theme

The permission relating to the system theme is used exclusively to automatically adapt the application's graphical interface to the light or dark mode configured on the user's device.

### Device Language and Interface Language

Upon first launch, the application may read the language configured on the device in order to automatically determine the interface language of the application.

The language determined in this way is used to configure the application's interface and, for authenticated users, may be saved in the database associated with the account in order to preserve the preference and synchronize it across devices.

The interface language is not used for profiling, tracking, or advertising purposes.

---

## 8. Absence of Advertising, Tracking, and Analytics Data Collection

G-Scanner adopts a strict privacy protection policy for its users.

The application:

* is completely free;

* contains no advertising;

* does not use analytics tools;

* does not use Google Analytics;

* does not use Firebase Crashlytics;

* does not perform user profiling;

* does not perform user tracking activities;

* does not sell personal data;

* does not communicate or transfer personal data to third parties for commercial purposes.

In particular, **G-Scanner does not collect advertising identifiers, application usage information, diagnostic data, or device technical data for analytical or profiling purposes**.

The application does not engage in behavioral monitoring processes of the user, nor does it create commercial or advertising profiles.

---

## 9. Data Retention

### 9.1 Anonymous Users

When the user uses G-Scanner without authenticating, personal data and configured preferences remain stored exclusively locally on the device via **SharedPreferences**.

Such data is retained until:

* the user deletes it via the features available in the application;

* the application is uninstalled;

* the device is reset or local data is cleared.

Product reports submitted to the community constitute a separate processing activity and are instead retained in the application's cloud database to allow consultation by other users.

### 9.2 Local Database for Offline Use

Data relating to products contained in the offline database is retained locally on the device until the user:

* deletes the database via the features available in the application;

* replaces the database with a different configuration;

* uninstalls the application;

* clears the relevant local data, where provided by the operating system.

The offline database may be updated periodically. The version available on the device may therefore not coincide with the most recent version of the data available online.

### 9.3 Authenticated Users

For authenticated users, data is retained using a **dual-storage** method:

* locally on the user's device, to enable swift application use;

* in the Firebase Firestore cloud database, to allow synchronization of information across different devices and maintenance of account-associated features.

Data associated with the account is retained until its deletion according to the procedures described in the following section on data erasure.

---

## 10. Right to Erasure and Account Management (Art. 17 GDPR)

The user has two distinct methods for managing the deletion of their data.

### 10.1 Account Deletion via Internal Application Feature

If the user utilizes the specific internal account deletion feature available in G-Scanner, the associated **Firebase Authentication profile** is deleted.

This operation entails:

* the permanent removal of the association between the account and the identifying data used for authentication;

* the deletion of references to email, first name, last name, and any provider data associated with the profile.

However, the deletion of the authentication profile **does not automatically trigger the immediate physical destruction of documents present in Firebase Firestore**.

Any data present in the cloud database, such as:

* scan history;

* application settings;

* data associated with the user identifier;

can no longer be linked to the user's identity and becomes technically inaccessible through normal use of the application.

The link between such data and the user's identity is permanently severed.

### 10.2 Complete and Permanent Data Erasure (Data Wipe)

Should the user require the complete and permanent physical erasure of all records associated with their identifier in cloud systems, they must submit an explicit request to the Data Controller via:

**[supporto-gscanner@googlegroups.com](mailto:supporto-gscanner@googlegroups.com)**

The request must be made **prior to proceeding with profile deletion via the application**, using the same email address associated with the account used for access.

This procedure is necessary so the Data Controller can verify the applicant's identity and correctly locate the records associated with the account.

If the user preemptively deletes their profile from the application without having sent the complete erasure request, it may no longer be possible to verify the applicant's identity and locate the data previously associated with the deleted account.

Following identity verification, the Data Controller will proceed with the permanent erasure of the data present in cloud systems associated with the user's identifier, within the limits technically available and required by applicable law.

---

## 11. Rights of the Data Subject

Pursuant to Articles 15 et seq. of the GDPR, the Data Subject may exercise the right to:

* obtain confirmation as to whether or not their personal data is being processed;

* access the personal data being processed;

* request the rectification of inaccurate data;

* request the erasure of data in cases provided by law;

* obtain the restriction of processing;

* object to processing in permitted cases;

* withdraw previously given consent, without affecting the lawfulness of processing carried out prior to withdrawal;

* receive their data in a structured format, where applicable (data portability);

* lodge a complaint with the Data Protection Supervisory Authority.

To exercise these rights, the Data Controller can be contacted at:

**[supporto-gscanner@googlegroups.com](mailto:supporto-gscanner@googlegroups.com)**

---

## 12. Data Security

Personal data is processed using IT tools and adequate technical and organizational measures to ensure its:

* confidentiality;

* integrity;

* availability;

* protection against unauthorized access.

In particular, for data stored via the Firebase infrastructure, access to cloud data is strictly limited to authorized personnel and is protected by technical and security measures provided by the Firebase infrastructure.

The Data Controller adopts measures proportionate to the nature of the data processed, taking into account the risks associated with processing, in compliance with Art. 32 GDPR.

---

## 13. Amendments to this Privacy Policy

The Data Controller reserves the right to amend or update this Privacy Policy to adapt it to:

* regulatory changes;

* technical evolutions of the application;

* variations in the methods of personal data processing.

The updated version will be made available within the application and/or through the official G-Scanner channels, indicating the date of the last update.

---

## 14. Service Providers and Data Transfer

To provide the features offered by G-Scanner, the Data Controller utilizes technological service providers who process personal data exclusively within the limits necessary for the execution of the requested services.

### 14.1 Cloud Infrastructure (Google Firebase)

For authentication and data storage features, G-Scanner uses the **Google Firebase** platform, provided by **Google Ireland Limited**, with offices at Gordon House, Barrow Street, Dublin 4, Ireland.

In particular, the application uses:

* **Firebase Authentication**, to manage user authentication;

* **Cloud Firestore**, to store and synchronize data for authenticated users.

For processing carried out on behalf of the Data Controller within the Firebase services used by the application, **Google Ireland Limited operates as a Data Processor pursuant to Art. 28 GDPR**.

This is without prejudice to any processing activities for which Google acts as an independent Data Controller as provided by the Firebase service privacy documentation.

### 14.2 Data Localization and Transfers to Third Countries

The **Cloud Firestore** database used by G-Scanner is configured in the region:

**eur3 – Frankfurt (Germany)**

which corresponds to infrastructures located within the European Union.

The Data Controller adopts this configuration to favor the retention of personal data within the European Economic Area (EEA).

Should Google execute technical transfers of personal data to countries outside the European Economic Area, such transfers will be carried out in compliance with Articles 44 et seq. of the GDPR and guaranteed by legally recognized instruments, including:

* the **EU-US Data Privacy Framework**, where applicable;

* the **Standard Contractual Clauses (SCCs)** approved by the European Commission.

### 14.3 Authentication Services via External Providers (Social Login)

The user can choose to authenticate via:

* Google;

* Facebook.

During the authentication process:

* **Google Ireland Limited**;

* **Meta Platforms Ireland Limited**

act as **Independent Data Controllers**, exclusively for activities necessary to verify credentials, manage digital identity, and provide the authentication service.

G-Scanner receives exclusively the data necessary for the creation and management of the account, which may include:

* first name;

* last name;

* email address;

* any available phone number.

For any further processing directly carried out by external providers, please refer to their respective official privacy policies:

* Google Privacy Policy;

* Meta Privacy Policy.

The Data Controller is not responsible for the processing carried out independently by these providers for their own purposes.

---

## 15. Absence of Automated Decision-Making (Art. 22 GDPR)

G-Scanner uses informational filters and criteria configured by the application to provide guidance on food products.

The classifications generated by the application, such as **"Forbidden"**, **"Allowed"**, **"Warning"**, or equivalent indications, exclusively constitute support information based on available data and user-selected settings.

**The application does not engage in automated decision-making processes producing legal effects concerning the user or similarly significantly affecting them pursuant to Art. 22 GDPR.**

---

## 16. Language of the Policies and Terms

This Privacy Policy, as well as the Terms of Service and any other legal documents related to the Application, were originally drafted in the Italian language. Any translations into other languages are provided solely as a courtesy and for the convenience of the User. In the event of any discrepancies, inconsistencies, or interpretative conflicts between the Italian language version and any translated version, the Italian language version shall strictly prevail, to the maximum extent permitted by applicable law.

---

## Data Controller Contacts

**Emanuele Ciotola**

E-mail:

**[supporto-gscanner@googlegroups.com](mailto:supporto-gscanner@googlegroups.com)**
''';
