// Copyright (c) 2026 Emanuele Ciotola. All Rights Reserved.
// PROJECT: G-Scanner — See LICENSE file in root for terms.

const String tosEn = r'''
# TERMS AND CONDITIONS OF USE (ToS)

## G-Scanner

**Version:** 1.0

**Effective Date:** October 9, 2026

**Last Updated:** October 9, 2026

---

This document governs the access to and use of the **G-Scanner** application (hereinafter, the "App").

Before using the App, the User is required to carefully read these **Terms and Conditions of Use** (hereinafter, the "Terms").

Accessing, registering, installing, or any use of the App constitutes electronic acceptance of these Terms and establishes a binding agreement between the User and the Developer, to the maximum extent permitted by applicable law.

If the User does not intend to fully agree to these Terms, they must strictly refrain from using the App.

---

## 1. Identity of the Developer and Nature of the Project

The **G-Scanner** App is developed and operated by:

**Emanuele Ciotola**

Contact for support, requests, or communications:

**[supporto-gscanner@googlegroups.com](mailto:supporto-gscanner@googlegroups.com)**

G-Scanner is a software project that is:

* **free of charge**;

* **amateur-built**;

* **non-commercial**;

* developed as a personal project by a computer science student.

The App is provided for informational, technical, and experimental purposes and does not constitute a professional, commercial, medical, healthcare, or nutritional service.

The Developer does not act as a food manufacturer, certifying body, nutritional consultant, doctor, or healthcare professional.

---

## 2. Age Requirements

The use of the App is strictly limited to users who are at least **14 (fourteen) years of age**.

By using the App, the User represents and warrants that they meet this age requirement.

The Developer assumes no responsibility for the use of the App by individuals who do not meet this requirement.

If the Developer becomes aware of the presence of data belonging to a minor under 14 years of age, such data will be deleted to the extent technically possible and in compliance with any applicable legal obligations.

---

## 3. Acceptance of Terms and Electronic Consent

Any use of the App, in any of its forms, including:

* the Web App;

* the Android application distributed via an **.apk** file;

* any future versions made available by the Developer;

constitutes full acceptance of these Terms.

Accessing, registering via available authentication systems, or simply utilizing the App's features constitutes a form of **binding electronic acceptance** of these Terms under applicable law.

The User acknowledges that such electronic acceptance produces legal effects equivalent to the acceptance of contractual conditions through traditional means, to the extent permitted by law.

Failure to comply with even a single provision of these Terms may result in the suspension, limitation, or termination of access to the App's services.

---

## 4. Nature of Service, Informational Purposes, and Medical Disclaimer

### 4.1 No medical purposes

**G-Scanner is not a medical device, does not constitute a diagnostic tool, and does not provide medical, nutritional, or healthcare advice.**

The App does not perform diagnoses, does not certify food safety, and does not replace the advice of doctors, nutritionists, or other qualified professionals.

The information displayed by the App is solely of an:

* informational;

* guidance-oriented;

* experimental nature.

The scan results, including but not limited to the indicators:

* **Green Light (Safe)**;

* **Yellow Light (Uncertain)**;

* **Red Light (Forbidden)**;

are generated by automated algorithms based on data available from internal and/or third-party sources.

These results must not be interpreted as:

* food certifications;

* medical evaluations;

* absolute guarantees of safety;

* personalized professional guidance.

---

### 4.2 No professional relationship

The use of the App does not create any:

* medical;

* healthcare;

* nutritional;

* consulting;

* professional relationship;

between the User and the Developer.

The information provided by the App does not constitute professional advice and must not be used as the sole basis for decisions regarding health or diet.

---

### 4.3 User's obligation to verify

The User acknowledges and agrees that they:

* are solely responsible for their own dietary decisions;

* must thoroughly read the physical label of the product before consumption;

* must personally verify ingredients, allergens, warnings, nutritional values, and any other information present on the original packaging.

The App does not in any way replace the manufacturer's official label.

---

### 4.4 Dietary preferences and personal data processing

The User acknowledges that certain Application settings related to personal dietary requirements may involve information potentially classified as special categories of personal data under Art. 9 of the GDPR.

The activation and use of features related to such preferences occur strictly in accordance with what is stated in the Application's Privacy Policy.

By using these features, the User declares to have read the corresponding privacy notice and to have provided, where required, the consent mandated by applicable law.

The User may modify or disable these preferences at any time through the options available in the Application, without affecting the lawfulness of processing based on consent before its withdrawal.

---

### 4.5 Liability and Indemnification Clause

To the maximum extent permitted by applicable law and without prejudice to the mandatory statutory rights of the User as a consumer, the User acknowledges that:

* the consumption of any food product is a personal choice;

* the final decision regarding the purchase and consumption of a product lies solely with the User.

The Developer shall not be held liable for:

* allergic reactions;

* intolerances;

* adverse effects;

* consequences arising from the consumption of products;

* classification errors;

* incomplete data;

* inaccurate information;

* algorithmic errors;

* personal interpretations of the results provided by the App.

The User agrees to indemnify and hold the Developer harmless from any claims, disputes, or demands arising directly from the improper use of the App or from independent decisions made based on the displayed information, to the maximum extent permitted by applicable law and without prejudice to the mandatory statutory rights of the User as a consumer.

---

## 5. Third-Party Data (Open Food Facts)

The App uses data from the **Open Food Facts** collaborative database.

This data is provided by users and contributors from the international community and is distributed under the **Open Database License (ODbL)**.

The Developer:

* does not create this data;

* does not directly control its input;

* does not guarantee its accuracy;

* does not guarantee its completeness;

* does not guarantee it is up-to-date;

* does not guarantee the absence of errors or omissions.

The User acknowledges that any inaccuracies, omissions, or outdated data present in the Open Food Facts database cannot be attributed to the Developer.

The User further acknowledges that **Open Food Facts operates as an independent collaborative database and that G-Scanner merely utilizes such information without necessarily certifying or modifying its original content.**

In particular, G-Scanner does not certify the regulatory compliance of food products, their safety, or the accuracy of the information present on the manufacturers' labels.

Any data stored locally to enable offline operation may also be subject to delays in updates compared to the data available online.

---

## 6. Application Distribution, APK Installation, and External Services

The App is made available:

* as a Web App via GitHub Pages;

* as an Android application distributed via an **.apk** file.

The manual installation of APK files from sources outside official app stores ("sideloading") is a voluntary choice of the User and is done at their own exclusive risk.

The Developer assumes no liability for:

* installation errors;

* hardware or software incompatibilities;

* modifications made by the User;

* incorrect device configurations;

* issues arising from enabling installations from unknown sources;

* damages arising from the environment of the device used.

---

### 6.1 Infrastructural services and external providers

For the operation of the App, services provided by third parties may be used, including, but not limited to:

* GitHub Pages;

* Firebase;

* hosting services;

* database services;

* cloud services;

* external APIs.

The Developer does not directly control these services and is not responsible for:

* malfunctions;

* temporary outages;

* technical modifications;

* suspensions;

* service terminations;

* API changes;

* loss of availability;

attributable to the respective third-party providers.

The User acknowledges that such services are subject to the terms, conditions, and policies of their respective providers.

---

## 7. User Account, Social Login, and Community Reports

### 7.1 Account creation and management

Certain features of the App may require User authentication through login systems provided by third parties ("Social Login"), including, but not limited to:

* Google;

* Facebook;

* any other authentication providers potentially integrated in the future.

Logging in via these systems implies that certain information related to the account identity may be managed through the respective external providers, according to their terms of service and privacy policies.

The User acknowledges being solely responsible for the security of their Google, Facebook, or other provider account used for authentication.

The Developer does not manage, know, or store the passwords or login credentials of the external accounts used by the User.

Any activity performed through such accounts remains under the responsibility of the respective account holder, except as otherwise provided by applicable law.

The Developer is not responsible for:

* unauthorized access resulting from the compromise of the User's account;

* loss of credentials with external providers;

* security breaches of the User's device;

* malfunctions, modifications, suspensions, or terminations of authentication services provided by Google, Facebook, or other third-party providers.

---

### 7.2 Account deletion request

The User may request the deletion of their account and associated data through:

* the tools potentially available directly within the App;

* the official support channels indicated in these Terms.

The Developer will process the request to the extent technically possible and in compliance with any applicable legal obligations.

Account deletion may result in the permanent loss of the features associated with it and any contributions linked to the account.

---

### 7.3 User Reports

Authenticated users can contribute to the improvement of the service by submitting reports regarding products in the G-Scanner database.

Reports may consist exclusively of:

* texts;

* descriptive information;

* data;

* product-related notes.

The App does not allow the uploading of photographs or images via such reports, subject to future modifications communicated by the Developer.

The User commits to submitting information that is solely:

* truthful;

* relevant;

* made in good faith.

It is expressly strictly prohibited to:

* submit false reports;

* input deliberately incorrect information;

* submit misleading content;

* engage in spamming activities;

* compromise the quality of the database;

* use offensive or unlawful language;

* cause harm to the App or the community.

---

### 7.4 License on User-submitted content

By submitting reports via the App, the User grants the Developer a free, non-exclusive license, valid for the duration necessary for the management, maintenance, and improvement of the Application and the G-Scanner database, and usable to the extent permitted by law, over the textual and informational content provided.

This license is limited to the purposes stated above and cannot be used for other purposes.

For this purpose, the Developer may:

* store such content;

* analyze it;

* modify it where necessary for technical purposes;

* integrate it into the Application's database;

* use it to improve the functioning of the service.

This license does not entail:

* a transfer of ownership of the content;

* a waiver of any rights potentially belonging to the User;

* authorization to use such content for purposes unrelated to the management and improvement of G-Scanner.

---

### 7.5 Right to suspend and remove account

The Developer reserves the exclusive right to:

* temporarily suspend an account;

* limit certain features;

* delete an account;

* remove reports;

* prevent further contributions;

if they believe, in their reasonable and discretionary judgment, that the User's behavior is:

* in breach of these Terms;

* fraudulent;

* harmful to the community;

* harmful to the technical functioning of the App;

* likely to compromise the quality of the database.

Such a decision may be taken even without prior notice in cases where it is necessary to protect the security, integrity, or proper functioning of the service.

---

## 8. Intellectual Property of the Application

All intellectual property rights related to G-Scanner, including, but not limited to:

* source code;

* compiled code;

* algorithms;

* data structures;

* graphical interface;

* visual elements;

* application logic;

* software architecture;

* the name of the App;

belong exclusively to **Emanuele Ciotola**, except for any third-party components governed by their respective licenses.

The fact that the App's source code is publicly viewable via GitHub is exclusively for the purposes of:

* transparency;

* technical verification;

* studying its functioning.

The publication of the code does not constitute:

* the granting of an Open Source license;

* authorization for free reuse;

* a waiver of intellectual property rights;

* a transfer of rights to third parties.

---

## 9. Code License and Usage Limitations

The App's code is distributed under a **Source-Available** model with a proprietary **"All Rights Reserved"** license.

The ability to view the source code does not grant the User any right to:

* freely use the software;

* modify it;

* distribute it;

* create derivative works;

* commercialize it.

Unless explicitly authorized in writing by the Developer, it is strictly prohibited to:

* copy the code in whole or in part;

* clone the project;

* reproduce the algorithm;

* replicate the operating logic;

* reproduce the UI;

* create derivative versions;

* distribute copies of the App;

* use code components for other projects;

* commercially exploit the software.

It is furthermore prohibited to perform:

* reverse engineering;

* decompilation;

* disassembly;

* code analysis aimed at reconstructing internal logic;

* scraping of the algorithms;

* automated extraction of software components;

* reconstruction of the Application's internal functioning.

Any unauthorized use may result in the exercise of legal remedies provided by applicable law, including claims for compensation for damages incurred.

These limitations apply to the maximum extent permitted by applicable law and are not intended to restrict any mandatory rights recognized by law, including those related to software interoperability where applicable.

---

## 10. Limited License to Use the Application

The Developer grants the User a license that is:

* personal;

* limited;

* non-exclusive;

* revocable;

* non-transferable;

to use G-Scanner exclusively for lawful, personal purposes.

The license exclusively allows:

* access to the available features;

* the use of the App in accordance with these Terms;

* the consultation of the information provided.

This license does not entail any transfer of:

* ownership of the App;

* rights to the code;

* rights to the algorithms;

* rights to the UI;

* economic exploitation rights.

Any rights not expressly granted remain reserved by the Developer.

---

## 11. Availability, Updates, and Software Evolution

### 11.1 Modifications and service evolution

The User acknowledges that G-Scanner is a continuously evolving software.

The Developer may modify, update, improve, suspend, or discontinue features of the App at any time, even without prior notice, when necessary for technical, organizational, security, or development reasons.

By way of example, the Developer may:

* modify algorithms;

* update components;

* change operating modes;

* introduce new features;

* remove existing features;

* temporarily suspend the service.

The Developer does not guarantee:

* continuous availability;

* the absolute absence of errors;

* permanent compatibility with every device;

* the indefinite maintenance of all features.

Such modifications do not automatically grant the User the right to compensation, refunds, or damages, to the maximum extent permitted by applicable law and without prejudice to the mandatory statutory rights of the User as a consumer.

### 11.2 Offline mode and local databases

G-Scanner may offer an offline mode that allows the User to use certain features of the Application without an active Internet connection.

To enable offline use, the Application may make available to the User different variants of a local database, characterized by different sizes and amounts of data. The User may choose and download the variant best suited to their needs and the available storage space on their device.

The availability, content, sizes, number of variants, and features supported by offline databases may be modified, updated, limited, or removed by the Developer at any time.

The data contained in the local database may also be less up to date than the data available online. The use of offline mode does not modify or diminish the User's obligations to personally and thoroughly verify the information stated on the original packaging of products prior to consumption.

---

## 12. Fair Use, Security, and Prohibition of Technical Abuse

The User agrees to use G-Scanner in a fair and proper manner, in compliance with the law, these Terms, and the principles of good faith.

The User is obligated not to use the App in a way that compromises:

* the security of the service;

* the availability of the Application;

* the integrity of the IT systems;

* the experience of other users;

* the quality of the managed data.

It is strictly prohibited, without prior written authorization from the Developer, to:

* perform automated scraping of data, interfaces, or features of the App;

* use bots, crawlers, or automated tools to access the service;

* send an excessive or unreasonable number of requests to the systems or APIs;

* attempt to overload servers, databases, or infrastructures used by the App;

* bypass security systems, authentication protocols, or technical limitations;

* attempt to gain unauthorized access to data or confidential components;

* interfere with the normal operation of the Application;

* introduce malicious code, malware, or potentially harmful components;

* perform reverse engineering, decompilation, or activities aimed at reconstructing the internal functioning of the App.

Any behavior capable of compromising the security, stability, or availability of the service may result in the suspension or termination of the User's access, in addition to the possible exercise of legal remedies provided by applicable law.

---

## 13. Electronic Communications

The User agrees to receive electronic communications strictly necessary for the management of the relationship with the Developer and for the proper functioning of the App.

Such communications may involve:

* technical updates;

* security-related information;

* amendments to these Terms;

* significant modifications to the App's features;

* administrative communications related to the account;

* information necessary for managing the service.

These communications serve exclusively technical, administrative, or service-related purposes and do not automatically constitute commercial or promotional messages.

Any promotional communications will be subject to any consents required by applicable law.

---

## 14. External Services, Third-Party Infrastructure, and Providers

For the operation of the App, services provided by third parties may be used, including, but not limited to:

* authentication services;

* cloud services;

* external databases;

* hosting services;

* GitHub Pages;

* Firebase;

* third-party APIs and technological infrastructures.

The User acknowledges that these services are independently managed by their respective providers and are subject to their specific contractual terms, conditions of use, and privacy policies.

To the maximum extent permitted by applicable law and without prejudice to the mandatory statutory rights of the User as a consumer, the Developer is not responsible for:

* temporary outages of external services;

* malfunctions of providers;

* technical modifications made by third parties;

* suspension or termination of APIs;

* changes in the conditions of external services;

* loss of availability of infrastructures not directly controlled by the Developer.

---

## 15. General Limitation of Liability

To the maximum extent permitted by applicable law and without prejudice to the mandatory statutory rights of the User as a consumer, G-Scanner is provided:

**"AS IS"**

and

**"AS AVAILABLE"**.

The Developer does not guarantee that:

* the App will be available without interruptions;

* the service will be error-free;

* all features will always be fully operational;

* the data used will always be complete or up-to-date;

* the results produced will always be free from inaccuracies;

* the App will be compatible with every device or technical configuration.

The Developer shall not be held liable for damages arising from the use of the App, except in cases where such liability cannot be excluded or limited under applicable law.

In particular, nothing in these Terms limits or excludes:

* mandatory statutory rights granted to consumers by Italian and European law;

* liability arising from willful misconduct or gross negligence where provided by law;

* any other liability that cannot be legally excluded.

---

## 16. Privacy Policy and Cookie Policy

The processing of Users' personal data is governed by a specific **Privacy Policy**, which is a separate and independent document from these Terms.

The Privacy Policy governs, among other aspects:

* what personal data is collected;

* the purposes of the processing;

* the methods of data usage and the cloud architectures involved;

* any third-party services involved;

* the rights granted to data subjects under applicable law.

Within the same Privacy Policy, all information regarding the use of technical cookies and local storage technologies (e.g., SharedPreferences or LocalStorage) is provided. These are used by the App strictly for technical and operational necessities, without any tracking for advertising purposes.

These Terms and Conditions of Use:

* do not replace the Privacy Policy;

* do not constitute a privacy notice;

* do not exhaustively govern the processing of personal data.

The User is invited to consult these documents prior to using the App.

---

## 17. Amendments to the Terms

The Developer reserves the right to modify, amend, or update these Terms at any time.

Modifications may become necessary, for example, due to:

* technical evolution of the App;

* regulatory changes;

* the introduction of new features;

* security requirements;

* organizational updates.

The updated version of the Terms will be identified by the indication of the relevant version number and the date of the last update.

Modifications will take effect upon their publication through the official channels of the App.

Continued use of the Application following the publication of the modifications constitutes acceptance of the new version of the Terms.

If the User does not intend to accept the modifications, they must discontinue the use of the App and may request the deletion of their account according to the provided procedures.

---

## 18. Language of the Terms and Policies

These Terms and Conditions of Use, as well as the Privacy Policy and any further legal documents related to the Application, were originally drafted in Italian. Any translations into other languages are provided strictly as a courtesy and for the convenience of Users. In the event of any discrepancies, inconsistencies, ambiguities, or interpretative conflicts between the Italian language version and any translated version, the Italian language version shall strictly prevail, to the maximum extent permitted by applicable law.

---

## 19. Final Provisions

If any provision of these Terms is declared null, void, invalid, or unenforceable by a competent authority, such circumstance shall not affect the validity of the remaining provisions (Severability Clause).

The remaining provisions will continue to have full force and effect to the maximum extent permitted by applicable law.

Any failure by the Developer to exercise a right provided under these Terms does not constitute a permanent waiver of that right.

These Terms constitute the entire agreement between the User and the Developer regarding the use of the App, limited to the aspects governed within this document.

---

## 20. Applicable Law and Jurisdiction

These Terms are governed by **Italian law**, without prejudice to the mandatory provisions applicable under European Union law and Italian consumer protection laws.

For Users who qualify as consumers under applicable law, the mandatory rules regarding territorial jurisdiction and consumer protection shall remain applicable.

For Users who do not hold such qualification, any disputes arising from the interpretation, execution, or validity of these Terms shall be governed by Italian law and submitted to the competent court according to the applicable provisions.

---

## Contacts

**Application:** G-Scanner

**Developer:** Emanuele Ciotola

**Support E-mail:**

[supporto-gscanner@googlegroups.com](mailto:supporto-gscanner@googlegroups.com)
''';
